version: '3.9'
services:
  minio:
    image: minio/minio
    container_name: indarest-storage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: my-secure-pw
    volumes:
      - ../storage/minio:/data
    command: 'server /data --console-address ":9001"'