/*
 * This file is generated by jOOQ.
 */
package rest.mjis.indarest.infrastructure.database.jooq.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import rest.mjis.indarest.infrastructure.database.jooq.Mjis
import rest.mjis.indarest.infrastructure.database.jooq.keys.BOARD_PIN_MAPPERS_PKEY
import rest.mjis.indarest.infrastructure.database.jooq.keys.BOARD_PIN_MAPPERS_UQ_1
import rest.mjis.indarest.infrastructure.database.jooq.tables.records.BoardPinMappersRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BoardPinMappers(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BoardPinMappersRecord>?,
    parentPath: InverseForeignKey<out Record, BoardPinMappersRecord>?,
    aliased: Table<BoardPinMappersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BoardPinMappersRecord>(
    alias,
    Mjis.MJIS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>mjis.board_pin_mappers</code>
         */
        val BOARD_PIN_MAPPERS: BoardPinMappers = BoardPinMappers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BoardPinMappersRecord> = BoardPinMappersRecord::class.java

    /**
     * The column <code>mjis.board_pin_mappers.id</code>.
     */
    val ID: TableField<BoardPinMappersRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>mjis.board_pin_mappers.board_id</code>.
     */
    val BOARD_ID: TableField<BoardPinMappersRecord, Long?> = createField(DSL.name("board_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>mjis.board_pin_mappers.pin_id</code>.
     */
    val PIN_ID: TableField<BoardPinMappersRecord, Long?> = createField(DSL.name("pin_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>mjis.board_pin_mappers.created_at</code>.
     */
    val CREATED_AT: TableField<BoardPinMappersRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>mjis.board_pin_mappers.created_by_id</code>.
     */
    val CREATED_BY_ID: TableField<BoardPinMappersRecord, String?> = createField(DSL.name("created_by_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>mjis.board_pin_mappers.updated_at</code>.
     */
    val UPDATED_AT: TableField<BoardPinMappersRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<BoardPinMappersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BoardPinMappersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BoardPinMappersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>mjis.board_pin_mappers</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>mjis.board_pin_mappers</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>mjis.board_pin_mappers</code> table reference
     */
    constructor(): this(DSL.name("board_pin_mappers"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Mjis.MJIS
    override fun getIdentity(): Identity<BoardPinMappersRecord, Long?> = super.getIdentity() as Identity<BoardPinMappersRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<BoardPinMappersRecord> = BOARD_PIN_MAPPERS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<BoardPinMappersRecord>> = listOf(BOARD_PIN_MAPPERS_UQ_1)
    override fun `as`(alias: String): BoardPinMappers = BoardPinMappers(DSL.name(alias), this)
    override fun `as`(alias: Name): BoardPinMappers = BoardPinMappers(alias, this)
    override fun `as`(alias: Table<*>): BoardPinMappers = BoardPinMappers(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BoardPinMappers = BoardPinMappers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BoardPinMappers = BoardPinMappers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BoardPinMappers = BoardPinMappers(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BoardPinMappers = BoardPinMappers(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BoardPinMappers = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BoardPinMappers = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BoardPinMappers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BoardPinMappers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BoardPinMappers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BoardPinMappers = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BoardPinMappers = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): BoardPinMappers = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): BoardPinMappers = where(DSL.notExists(select))
}
