/*
 * This file is generated by jOOQ.
 */
package rest.mjis.indarest.infrastructure.database.jooq.tables


import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import rest.mjis.indarest.infrastructure.database.jooq.Mjis
import rest.mjis.indarest.infrastructure.database.jooq.keys.BOARDS_PKEY
import rest.mjis.indarest.infrastructure.database.jooq.tables.records.BoardsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Boards(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BoardsRecord>?,
    parentPath: InverseForeignKey<out Record, BoardsRecord>?,
    aliased: Table<BoardsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BoardsRecord>(
    alias,
    Mjis.MJIS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>mjis.boards</code>
         */
        val BOARDS: Boards = Boards()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BoardsRecord> = BoardsRecord::class.java

    /**
     * The column <code>mjis.boards.id</code>.
     */
    val ID: TableField<BoardsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>mjis.boards.name</code>.
     */
    val NAME: TableField<BoardsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(256).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>mjis.boards.created_at</code>.
     */
    val CREATED_AT: TableField<BoardsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>mjis.boards.created_by_id</code>.
     */
    val CREATED_BY_ID: TableField<BoardsRecord, String?> = createField(DSL.name("created_by_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>mjis.boards.updated_at</code>.
     */
    val UPDATED_AT: TableField<BoardsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<BoardsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BoardsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BoardsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>mjis.boards</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>mjis.boards</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>mjis.boards</code> table reference
     */
    constructor(): this(DSL.name("boards"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Mjis.MJIS
    override fun getIdentity(): Identity<BoardsRecord, Long?> = super.getIdentity() as Identity<BoardsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<BoardsRecord> = BOARDS_PKEY
    override fun `as`(alias: String): Boards = Boards(DSL.name(alias), this)
    override fun `as`(alias: Name): Boards = Boards(alias, this)
    override fun `as`(alias: Table<*>): Boards = Boards(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Boards = Boards(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Boards = Boards(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Boards = Boards(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Boards = Boards(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Boards = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Boards = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Boards = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Boards = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Boards = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Boards = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Boards = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Boards = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Boards = where(DSL.notExists(select))
}
