/*
 * This file is generated by jOOQ.
 */
package rest.mjis.indarest.infrastructure.database.jooq.tables.records


import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import rest.mjis.indarest.infrastructure.database.jooq.tables.BoardPinMappers


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BoardPinMappersRecord() : UpdatableRecordImpl<BoardPinMappersRecord>(BoardPinMappers.BOARD_PIN_MAPPERS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var boardId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var pinId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var createdById: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised BoardPinMappersRecord
     */
    constructor(id: Long? = null, boardId: Long? = null, pinId: Long? = null, createdAt: LocalDateTime? = null, createdById: String? = null, updatedAt: LocalDateTime? = null): this() {
        this.id = id
        this.boardId = boardId
        this.pinId = pinId
        this.createdAt = createdAt
        this.createdById = createdById
        this.updatedAt = updatedAt
        resetChangedOnNotNull()
    }
}
