/*
 * This file is generated by jOOQ.
 */
package rest.mjis.indarest.infrastructure.database.jooq.tables.records


import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import rest.mjis.indarest.infrastructure.database.jooq.tables.Pins


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PinsRecord() : UpdatableRecordImpl<PinsRecord>(Pins.PINS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var resourceUrl: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var createdById: Long?
        set(value): Unit = set(5, value)
        get(): Long? = get(5) as Long?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var thumbnailUrl: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised PinsRecord
     */
    constructor(id: Long? = null, name: String? = null, description: String? = null, resourceUrl: String? = null, createdAt: LocalDateTime? = null, createdById: Long? = null, updatedAt: LocalDateTime? = null, thumbnailUrl: String? = null): this() {
        this.id = id
        this.name = name
        this.description = description
        this.resourceUrl = resourceUrl
        this.createdAt = createdAt
        this.createdById = createdById
        this.updatedAt = updatedAt
        this.thumbnailUrl = thumbnailUrl
        resetChangedOnNotNull()
    }
}
