/*
 * This file is generated by jOOQ.
 */
package rest.mjis.indarest.infrastructure.database.jooq.tables.references


import rest.mjis.indarest.infrastructure.database.jooq.tables.BoardPinMappers
import rest.mjis.indarest.infrastructure.database.jooq.tables.Boards
import rest.mjis.indarest.infrastructure.database.jooq.tables.Pins
import rest.mjis.indarest.infrastructure.database.jooq.tables.Users



/**
 * The table <code>mjis.board_pin_mappers</code>.
 */
val BOARD_PIN_MAPPERS: BoardPinMappers = BoardPinMappers.BOARD_PIN_MAPPERS

/**
 * The table <code>mjis.boards</code>.
 */
val BOARDS: Boards = Boards.BOARDS

/**
 * The table <code>mjis.pins</code>.
 */
val PINS: Pins = Pins.PINS

/**
 * The table <code>mjis.users</code>.
 */
val USERS: Users = Users.USERS
